title: Sumit Khatri
logo: /assets/img/Profile_Pic.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  A home page to expand on my data science projects. All source code can be found on my GitHub profile!
  <br><br>  
  Please Contact for Resume. 
    <br><br>  
    Email: sumitkhatri@tamu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/sumit-khatri-99499573">View LinkedIn Profile</a>   
  
theme: jekyll-theme-minimal
classes: wide
