title: Sumit Khatri
logo: <img src="assets/img/Profile.jpg?raw=true" width="25%" height="25%">
description: > # your text below (remove <br> elements if you don't need line breaks)
  Explore to know more about my work!
  <br><br>  
  Please Contact for Resume. 
    <br><br>  
    Email: sumitkhatri@tamu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/sumit-khatri-99499573">View LinkedIn Profile</a>   
    <br><br>
  <a href="https://scholar.google.com/citations?user=TCVTLH0AAAAJ&hl=en">View Google Scholar</a>   
  
theme: jekyll-theme-minimal
classes: wide
plugins:
    - jekyll-seo-tag
