title: Sumit Khatri
logo: /assets/img/Profile3.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Click on the headers on the right to know more about each project!
  <br><br>  
  Please Contact for Resume. 
    <br><br>  
    Email: sumitkhatri@tamu.edu
  <br><br>
  <a href="https://www.linkedin.com/in/sumit-khatri-99499573">View LinkedIn Profile</a>   
    <br><br>
  <a href="https://scholar.google.com/citations?user=TCVTLH0AAAAJ&hl=en">View Google Scholar</a>   
  
theme: jekyll-theme-minimal
classes: wide
plugins:
    - jekyll-seo-tag
